package torresra_java_rms;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Raven Torres
 */
public class AddProduct extends javax.swing.JFrame {

    private String Prod_id = "";
    private Connection conn;
    private PreparedStatement pstmt;

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        data();
        getCategory();
        showDate();
        showTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        addBtnP = new javax.swing.JButton();
        editBtnP = new javax.swing.JButton();
        deleteBtnP = new javax.swing.JButton();
        clearBtnP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        menuTxtField = new javax.swing.JTextField();
        priceTxtField = new javax.swing.JTextField();
        categoryDropdown = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        timeLab = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        categoryBtn3 = new javax.swing.JLabel();
        menuBtn3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dashboardBtn3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addOrderBtn = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 440, 120));

        productTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID#", "MENU", "CATEGORY", "PRICE"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setMinWidth(0);
            productTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            productTable.getColumnModel().getColumn(0).setMaxWidth(0);
            productTable.getColumnModel().getColumn(3).setMinWidth(110);
            productTable.getColumnModel().getColumn(3).setPreferredWidth(110);
            productTable.getColumnModel().getColumn(3).setMaxWidth(110);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 410, 210));

        addBtnP.setBackground(new java.awt.Color(0, 204, 51));
        addBtnP.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        addBtnP.setText("ADD");
        addBtnP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 1, true));
        addBtnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnPActionPerformed(evt);
            }
        });
        jPanel1.add(addBtnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 140, 40));

        editBtnP.setBackground(new java.awt.Color(0, 51, 255));
        editBtnP.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        editBtnP.setText("EDIT");
        editBtnP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true));
        editBtnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnPActionPerformed(evt);
            }
        });
        jPanel1.add(editBtnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 140, 40));

        deleteBtnP.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtnP.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        deleteBtnP.setText("DELETE");
        deleteBtnP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        deleteBtnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnPActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, 40));

        clearBtnP.setBackground(new java.awt.Color(204, 204, 204));
        clearBtnP.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        clearBtnP.setText("CLEAR");
        clearBtnP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        clearBtnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnPActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 140, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-small.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 290, 200));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));

        priceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtFieldActionPerformed(evt);
            }
        });

        categoryDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryDropdownActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Menu:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Category:");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Price:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(categoryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(menuTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 360, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("MENU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 10, 50));

        timeLab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeLab.setForeground(new java.awt.Color(0, 153, 51));
        timeLab.setText("time");
        jPanel7.add(timeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 147, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Time:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        dateLab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateLab.setForeground(new java.awt.Color(0, 102, 0));
        dateLab.setText("date");
        jPanel7.add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Date:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 510, 70));

        exitBtn.setBackground(new java.awt.Color(204, 204, 204));
        exitBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 153));
        exitBtn.setText("X");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, 40));

        jLabel22.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("MENU");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 930, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        jPanel23.setBackground(new java.awt.Color(255, 51, 0));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        jPanel13.setBackground(new java.awt.Color(255, 51, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category-icon (1).png"))); // NOI18N
        jLabel15.setText("jLabel2");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 55, 53));

        categoryBtn3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        categoryBtn3.setForeground(new java.awt.Color(255, 255, 255));
        categoryBtn3.setText("CATEGORY");
        jPanel14.add(categoryBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 90));

        menuBtn3.setBackground(new java.awt.Color(51, 51, 51));
        menuBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn3MouseClicked(evt);
            }
        });
        menuBtn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jLabel16.setText("jLabel2");
        menuBtn3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 67, 52));

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MENU");
        menuBtn3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, -1));

        jPanel13.add(menuBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, 90));

        dashboardBtn3.setBackground(new java.awt.Color(51, 51, 51));
        dashboardBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtn3MouseClicked(evt);
            }
        });
        dashboardBtn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dash-icon.png"))); // NOI18N
        jLabel18.setText("jLabel2");
        dashboardBtn3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 55, 53));

        jLabel21.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DASHBOARD");
        dashboardBtn3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        jPanel13.add(dashboardBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 90));

        addOrderBtn.setBackground(new java.awt.Color(51, 51, 51));
        addOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOrderBtnMouseClicked(evt);
            }
        });
        addOrderBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale-icon.png"))); // NOI18N
        jLabel25.setText("jLabel2");
        addOrderBtn.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 65));

        jLabel23.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ADD ORDER");
        addOrderBtn.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 81, -1));

        jPanel13.add(addOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 100, -1));

        logoutBtn.setBackground(new java.awt.Color(51, 51, 51));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon.png"))); // NOI18N
        jLabel27.setText("jLabel2");
        logoutBtn.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 53, 65));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LOG OUT");
        logoutBtn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel13.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 100, 90));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOrderBtnMouseClicked
        setVisible(false);
        new AddOrder().setVisible(true);
    }//GEN-LAST:event_addOrderBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
       setVisible(false);
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void categoryDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryDropdownActionPerformed

    private void priceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtFieldActionPerformed

    private void clearBtnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnPActionPerformed
        this.menuTxtField.setText("");
        this.categoryDropdown.setSelectedItem("dessert");
        this.priceTxtField.setText("");
    }//GEN-LAST:event_clearBtnPActionPerformed

    private void deleteBtnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnPActionPerformed

        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.valueOf(Prod_id);
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/torresjavarms", "root", "");
                pstmt = conn.prepareStatement("DELETE FROM product_table WHERE product_id=? ");
                pstmt.setInt(1, id);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Succesfully Deleted");
                data();
                conn.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_deleteBtnPActionPerformed

    private void editBtnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnPActionPerformed

        String product_name = menuTxtField.getText();
        Object product_category = categoryDropdown.getSelectedItem();
        int product_price = parseInt(priceTxtField.getText());

        if (product_name.isEmpty() || Prod_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please click the table first...");
        } else {
            try {
                int id = Integer.valueOf(Prod_id);
                Class.forName("com.mysql.jdbc.Driver");

                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/torresjavarms", "root", "");
                pstmt = conn.prepareStatement("UPDATE product_table SET product_name= ? , product_category=? , product_price=? WHERE product_id=? ");

                pstmt.setString(1, product_name);
                pstmt.setObject(2, product_category);
                pstmt.setInt(3, product_price);
                pstmt.setInt(4, id);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Succesfully Updated");
                data();

                conn.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_editBtnPActionPerformed

    private void addBtnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnPActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/torresjavarms", "root", "");
            Statement stmt = (Statement) conn.createStatement(); //get the connection stream(connection port)
            String query = "INSERT INTO `product_table`(`product_name`,`product_category`, `product_price`) VALUES ('" + this.menuTxtField.getText() + "','" + this.categoryDropdown.getSelectedItem() + "','" + this.priceTxtField.getText() + "')";
            stmt.executeUpdate(query);
            conn.close();
            JOptionPane.showMessageDialog(this, "Successfully Added.");
            data();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_addBtnPActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        int selectedIndex = productTable.getSelectedRow();
        Prod_id = model.getValueAt(selectedIndex, 0).toString();
        menuTxtField.setText(model.getValueAt(selectedIndex, 1).toString());
        categoryDropdown.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
        priceTxtField.setText(model.getValueAt(selectedIndex, 3).toString());
    }//GEN-LAST:event_productTableMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void dashboardBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtn3MouseClicked
         setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_dashboardBtn3MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
         setVisible(false);
        new AddCategory().setVisible(true);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void menuBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn3MouseClicked
        setVisible(false);
        new AddProduct().setVisible(true);
    }//GEN-LAST:event_menuBtn3MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtnP;
    private javax.swing.JPanel addOrderBtn;
    private javax.swing.JLabel categoryBtn3;
    private javax.swing.JComboBox<String> categoryDropdown;
    private javax.swing.JButton clearBtnP;
    private javax.swing.JPanel dashboardBtn3;
    private javax.swing.JLabel dateLab;
    private javax.swing.JButton deleteBtnP;
    private javax.swing.JButton editBtnP;
    private javax.swing.JButton exitBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel menuBtn3;
    private javax.swing.JTextField menuTxtField;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel timeLab;
    // End of variables declaration//GEN-END:variables

    private void data() {
        DefaultTableModel dm = (DefaultTableModel) productTable.getModel();
        dm.setRowCount(0);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/torresjavarms", "root", "");
            PreparedStatement insert = conn.prepareStatement("select * from product_table");
            ResultSet result = insert.executeQuery();

            DefaultTableModel model = (DefaultTableModel) productTable.getModel();
            while (result.next()) {
                model.addRow(new Object[]{result.getInt("product_id"),result.getString("product_name"), result.getObject("product_category"), result.getInt("product_price")});
                
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void getCategory() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/torresjavarms", "root", "");
            Statement stmt = conn.createStatement(); 
            ResultSet rs = stmt.executeQuery("SELECT * FROM category_table");
            while (rs.next()) {
                String category = rs.getString("category");
                categoryDropdown.addItem(category);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void showDate(){
        Date today = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM-dd-yyyy");
        String strdate = s.format(today);
        dateLab.setText(strdate);;
    }
    public void showTime(){       
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date time = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                String strtime = s.format(time);
                timeLab.setText(strtime);
            }
        }).start();
    }
}
